version: '3'
services:
  phpcli:
    build: docker/phpcli
    tty: true
    command: sh
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  broker:
    image: 'rabbitmq:3.7.14-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
  nri:
    build:
      context: docker/nri
    tty: true
    environment:
      NR_LICENSE_KEY: ${NR_LICENSE_KEY}
      RABBITMQ_ENDPOINT: broker
      RABBITMQ_PORT: 15672
      RABBITMQ_USE_SSL:  'false'
      RABBITMQ_USERNAME: ${RABBIT_USER}
      RABBITMQ_PASSWORD:  ${RABBIT_PASSWORD}
      QUEUES_REGEXES: '["^import\."]'
      EXCHANGES_REGEXES: '["^import\."]'
